import Head from "next/head";
import Image from "next/image";

import { Header, Layout, Navigation, Text } from "../../components/";

import pages from "./data";

export default function AdinkraAcknowledgements() {
	return (
		<div>
			<Head>
				<title>Acknowledgements | CSDT</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navigation />
			<Layout pages={pages}>
				<Header>Acknowledgements</Header>
				<Text>
					Adinkra are symbols created by the Ashanti people of Ghana. Traditionally, Adinkra symbols were stamped onto
					cloth, but today they can be found throughout Ghana -- on water bottle labels, chairs, and architecture -- and
					they even appear elsewhere in the world where African people have traveled. Each symbol represents a certain
					belief or proverb, but their shapes also have deep mathematical significance, especially in the ways that they
					use logarithmic curves to represent organic growth. On this site you will learn about the origins of these
					symbols, what they mean, and how to identify the mathematics of Adinkra. You will then learn a simple
					programming language that allows you to simulate traditional Adinkra shapes, and even create your own original
					designs!
				</Text>

				<h3>Website</h3>
				<ul>
					<li>William Babbitt</li>
					<li>Jason Bernotsky</li>
					<li>Jon Charleston-Coad</li>
					<li>Ron Eglash</li>
					<li>Charles Hathaway</li>
					<li>Mukkai Krishnamoorthy</li>
					<li>Mae-Ling Lokko</li>
					<li>Samaria Mitchell</li>
					<li>Lindsay Poirier</li>
					<li>Jordan Vener</li>
					<li>Andrew Hunn</li>
				</ul>

				<h3>Research</h3>
				<ul>
					<li>William Babbitt</li>
					<li>Audrey Bennett</li>
					<li>Enoch Bulley</li>
					<li>Michael Lachney</li>
				</ul>

				<h3>Culture</h3>
				<ul>
					<li>Paul Nyamaah Boakye</li>
					<li>Gabriel Boyake</li>
				</ul>

				<h3>Photos</h3>
				<ul>
					<li>David Banks</li>
					<li>Dan Lyles</li>
				</ul>
			</Layout>
		</div>
	);
}
