import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { computing } from "./data";

import { Fragment } from "react";
import Navigation from "../components/Navigation";
export default function Home() {
	return (
		<>
			<Head>
				<title>CSDT</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navigation />
			<main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 bg-gray-100">
				<section className="grid md:grid-cols-2 grid-cols-1 pt-8 md:pt-16 ">
					<div className="flex flex-col justify-around">
						<h1 className="font-semibold text-4xl">Applications</h1>
						<div>
							<h2 className="font-thin text-2xl">Theme</h2>
							<section className="flex gap-3 flex-wrap">
								<button className="bg-gray-500 px-3 py-1 rounded-sm text-gray-50 hover:bg-gray-400 transition ease-linear duration-75">
									Computing
								</button>
								<button className="bg-gray-500 px-3 py-1 rounded-sm text-gray-50 hover:bg-gray-400 transition ease-linear duration-75">
									Culture
								</button>
								<button className="bg-gray-500 px-3 py-1 rounded-sm text-gray-50 hover:bg-gray-400 transition ease-linear duration-75">
									Mathematics
								</button>
								<button className="bg-gray-500 px-3 py-1 rounded-sm text-gray-50 hover:bg-gray-400 transition ease-linear duration-75">
									Biology
								</button>
							</section>
						</div>
					</div>
					<article className=" text-base text-gray-800 leading-6 bg-gray-200 border border-gray-300 rounded-md p-5 order-first md:order-last ">
						<p className="mb-2">
							The elitist myths of &quot;savages&quot; and &quot;white trash&quot; led to today&apos;s bigotry. Here you
							can counter those stereotypes with African fractals, Appalachian quilting algorithms and more. From Native
							beadwork to urban graffiti, students can find the “heritage algorithms” of their interest, learn their
							connection to STEM principles, and develop designs of their own creation.
						</p>

						<p className="mb-4">Learn, create, and share your work with Culturally Situated Design Tools!!</p>

						<div className="flex justify-between ">
							<a href="/starting" className="text-blue-600 hover:text-blue-500">
								More...
							</a>
							<a href="/help" className="text-blue-600 hover:text-blue-500">
								Teacher&apos;s Guide
							</a>
						</div>
					</article>
				</section>

				<section>
					{computing.map((category) => (
						<Fragment key={category.title}>
							<h3 className="text-2xl mt-16">
								{category.title} <span className="text-gray-800 text-base">{category.subtitle}</span>
							</h3>

							<div className="grid md:grid-cols-6 gap-4 ">
								{category.tools.map((tool) => (
									<a
										href={tool.directory}
										key={tool.name}
										className="w-full h-full bg-white p-2 text-center text-blue-800 hover:shadow-md hover:text-blue-500">
										<div className="w-full relative aspect-1">
											<Image src={tool.thumbnail} alt="" fill={true} />
										</div>
										<p className="leading-10 my-4">{tool.name}</p>
									</a>
								))}
							</div>
						</Fragment>
					))}
				</section>
			</main>

			<footer className="h-16 bg-gray-100"></footer>
		</>
	);
}
