import Head from "next/head";
import Image from "next/image";

import beyonce from "../../assets/henna/beyonce.png";
import Layout from "../../components/Layout";
import Navigation from "../../components/Navigation";

import pages from "./data";

export default function HennaBackground() {
	return (
		<>
			<Head>
				<title>Henna Background | CSDT</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navigation />
			<Layout pages={pages}>
				<h1 className="font-light text-4xl mb-4">Henna Body Art</h1>
				<p className="text-lg">
					The cultures of India, Africa and the Middle East all have traditions of painting with henna dye on the skin.
					In India it is called “mehndi”, in North Africa it is called “anella”, and in West Africa “lalle”. The word
					henna comes from Arabic, so in the middle east “hinna” means both the dye and the design. On this site you can
					learn not only what henna designs mean, but also how to “think like a computer scientist”. That is, to see the
					patterns as a kind of “algorithm” (set of rules). This will allow you to create your own henna designs using
					the software, and help your community connect culture and computing.
				</p>
				<div className=" h-62 aspect-golden relative my-5 md:w-2/5 ">
					<Image src={beyonce} className=" rounded-md " alt={""} fill={true} />
				</div>
				<p className="text-sm text-gray-500">Beyoncé showing her henna designs</p>
			</Layout>
		</>
	);
}
