import Head from "next/head";
import Image from "next/image";

import img1 from "../../assets/henna/india1.png";
import img2 from "../../assets/henna/india2.png";
import img3 from "../../assets/henna/india3.png";
import img4 from "../../assets/henna/india4.png";

import Header from "../../components/Header";
import Layout from "../../components/Layout";
import Navigation from "../../components/Navigation";

import pages from "./data";

export default function HennaIndia() {
	return (
		<div>
			<Head>
				<title>India | CSDT</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navigation />
			<Layout pages={pages}>
				<Header>Henna in India</Header>
				<section className="grid grid-cols-8  gap-x-8 gap-y-10 my-4 items-center">
					<p className="col-span-4 text-lg text-gray-700">
						In India the henna designs are called mehndi. Staining the skin with plant dyes is an ancient Hindu
						tradition in India. The use of henna dye probably came with the introduction of Islam in the 12th century.
						Today henna ceremonies are used by everyone. Hindu, Muslim, Sikh, Zorastorian, Jain, Buddhist, and
						Christians all include mehndi in their wedding ceremonies in India.
					</p>

					<div className="col-span-2">
						<Image src={img1} alt="" />
					</div>
					<div className="col-span-2">
						<Image src={img2} alt="" />
					</div>
				</section>
				<p className=" text-lg text-gray-700 my-4">
					One of the oldest and most popular designs is the paisley. The oldest examples (7th century silk) show a fruit
					on a tree. One theory is that this represents the Indian mango. By repeating similar curved shapes at many
					scales, the henna artists are creating a complex mathematical form called “fractals”. The complexity means
					that the bride will have to sit still for a long time, so her friends have to keep her entertained. In this
					way henna brings everyone together.
				</p>

				<p className=" text-lg text-gray-700 my-4">
					Fractals are often used by scientists to model nature. But in Africa and India, you can see fractals in
					architecture. Just look for a repeating shape that changes size. In Indian architecture you can see examples
					in the arches: often big arches are made up of lots of little arches.{" "}
					<strong>Can you find the arch of arches in this Indian mehndi design?</strong>
				</p>
				<section className="grid grid-cols-8  gap-x-8 gap-y-10 items-center">
					<div className="col-span-4">
						<Image src={img3} alt="" className="rounded-md" />
					</div>
					<div className="col-span-4">
						<Image src={img4} alt="" className="rounded-md" />
					</div>
				</section>
			</Layout>
		</div>
	);
}
