import Head from "next/head";
import Image from "next/image";

import img1 from "../../assets/henna/mideast1.png";
import img2 from "../../assets/henna/mideast2.png";
import img3 from "../../assets/henna/mideast3.png";
import img4 from "../../assets/henna/mideast4.png";

import Header from "../../components/Header";
import Layout from "../../components/Layout";
import Navigation from "../../components/Navigation";

import pages from "./data";

export default function HennaMiddleEast() {
	return (
		<div>
			<Head>
				<title>Middle East | CSDT</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navigation />
			<Layout pages={pages}>
				<Header>Henna in North Africa and the Middle East</Header>

				<section className="grid grid-cols-1 md:grid-cols-10 gap-x-8 gap-y-10 items-center ">
					<p className=" md:col-span-8 text-lg text-gray-700">
						The earliest known use of henna dye was found in the hair of an Egyptian mummy from 3400 BCE (5,400 years
						ago!). She had dyed what we would now call “extensions” in her hair. One ancient design still popular today
						is the hamsa, a hand with an eye in the center. It is said to ward off the “evil eye” (a curse created by
						staring). This example is from the Marrakech Henna Art Cafe in Morocco. In North Africa it is called the
						hand of Miriam by Jews; the hand of Mary by Christians, and the hand of Fatima (Muhammad&apos;s first
						daughter) in Islam. Perhaps because henna is shared across many faiths, it often appears in peace
						celebrations.
					</p>
					<div className=" md:col-span-2 ">
						<div className="w-full relative aspect-1">
							<Image
								src={img1}
								alt="Henna tattoo of hamsa, a hand with an eye in the center"
								className="rounded-md"
								fill={true}
							/>
						</div>
					</div>
				</section>

				<section className="grid grid-cols-8  gap-x-8 gap-y-10 my-4 items-center">
					<p className="col-span-6 text-lg text-gray-700">
						Just because henna has ancient roots does not mean it is old-fashioned. Here you can see a henna artist in
						Morocco using a modern hypodermic to squirt henna paste into a design. In Morocco henna designs often use
						things associated with growth: growing vines, blossoming flowers, budding fruit, and so on. That is because
						henna ceremonies are often for getting married or having a baby.
					</p>

					<div className="col-span-2">
						<Image src={img2} alt="Henna artist using a hypodermic for design" className="rounded-md " />
					</div>
				</section>

				<section className="grid grid-cols-8  gap-x-8 gap-y-10 my-4 items-center">
					<p className="col-span-4 text-lg text-gray-700">
						North African groups such as the Tuareg and Amazigh (Berbers) have nomadic traditions in which women wove
						fabric for tents. Cynthia Becker, a professor of art history who interviewed women in these cultures, said
						that by making textiles and tattoos resemble each other, they are connecting their reproductive power as
						mothers with their artistic power as those who create and maintain tradition.
					</p>

					<div className="col-span-2">
						<Image src={img3} alt="Example of henna " />
					</div>
					<div className="col-span-2">
						<Image src={img4} alt="Example of a text" />
					</div>
				</section>
			</Layout>
		</div>
	);
}
