import Head from "next/head";
import Image from "next/image";

import img1 from "../../assets/henna/tut1.png";
import img2 from "../../assets/henna/tut2.png";
import img3 from "../../assets/henna/tut3.png";
import img4 from "../../assets/henna/tut4.png";
import Layout from "../../components/Layout";
import Navigation from "../../components/Navigation";

import pages from "./data";

import SoftwareCard from "../../components/SoftwareCard";

export default function HennaSoftware() {
	return (
		<div>
			<Head>
				<title>Henna Software | CSDT</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navigation />
			<Layout pages={pages}>
				<h1 className="font-light text-4xl mb-4">Henna Software</h1>
				<p className="text-lg">Create your own Henna patterns</p>
				<div className="flex items-stretch w-full content-center flex-row ">
					<SoftwareCard source={img1} link={"/applications/122/run"} name={"Flowers and Other Radial Patterns"} />
					<SoftwareCard source={img2} link={"/applications/123/run"} name={"Vines with Leaves"} />
					<SoftwareCard source={img3} link={"/applications/124/run"} name={"Curves with Dots and Spirals"} />
					<SoftwareCard source={img4} link={"/applications/125/run"} name={"Straight Lines"} />
				</div>
			</Layout>
		</div>
	);
}
