import Head from "next/head";
import Image from "next/image";

import img1 from "../../assets/henna/west1.png";
import img2 from "../../assets/henna/west2.jpg";

import Header from "../../components/Header";
import Layout from "../../components/Layout";
import Navigation from "../../components/Navigation";

import pages from "./data";

export default function HennaWestAfrica() {
	return (
		<div>
			<Head>
				<title>West Africa | CSDT</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navigation />
			<Layout pages={pages}>
				<Header>Henna in West Africa</Header>

				<section className="grid grid-cols-8  gap-x-8 gap-y-10 items-center my-4">
					<div className="col-span-4">
						<Image src={img1} alt="" className="rounded-md" />
					</div>
					<div className="col-span-4">
						<Image src={img2} alt="" className="rounded-md" />
					</div>
				</section>
				<p className=" text-lg text-gray-700">
					In West Africa the designs are not drawn on the skin. Rather thin strips create a design where the henna will
					not stain. Then the henna is applied everywhere. Once it is washed off, the strips can be removed. So the west
					African designs tend to use straight lines. When our research team was in Mali we asked what the repeated
					triangles meant. The women creating designs said they were the scales of a fish. With good luck you will catch
					a bigger fish each time, so that is why the triangles increase in size. Henna is not only carrying ancient
					traditions, but new innovations as well. One new technique is to arrange straight lines along a curve, so that
					the patterns look like leaves or feathers, as shown in this baby naming ceremony in Bamako, Mali (Photo by
					Katie Orlinsky).
				</p>
			</Layout>
		</div>
	);
}
